"""Type stubs for triad Python bindings."""

from typing import Optional, Any

__version__: str

class Transaction:
    async def execute(self, sql: str) -> int: ...
    async def fetch_optional(self, sql: str) -> Optional[str]: ...

class TransactionCM:
    async def __aenter__(self) -> Transaction: ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class TriadInstance:
    @staticmethod
    async def start(
        pg_url: str, redis_url: Optional[str] = None
    ) -> "TriadInstance": ...
    async def shutdown(self, timeout_secs: Optional[float] = None) -> None: ...
    def transaction(self) -> TransactionCM: ...

class OutboxPublisher:
    def __init__(
        self, table: str, kafka_topic: str, name: Optional[str] = None
    ) -> None: ...
    async def publish(
        self,
        tx: Transaction,
        aggregate_type: str,
        aggregate_id: str,
        event_type: str,
        payload: Any,
    ) -> str: ...

class FlagEvaluator:
    @staticmethod
    async def from_pg(pg_url: str) -> "FlagEvaluator": ...
    @staticmethod
    def from_flags(flags: dict[str, bool]) -> "FlagEvaluator": ...
    async def is_enabled(self, flag: str) -> bool: ...

class SagaStepConfig:
    name: str
    command_topic: str
    reply_topic: str
    compensation: Optional[str]
    timeout: Optional[str]

class SagaConfig:
    name: str
    trigger_topic: str
    trigger_event: str
    timeout: str
    steps: list[SagaStepConfig]

class SagaBuilder:
    def __init__(
        self,
        name: str,
        trigger_topic: str,
        trigger_event: str,
        timeout: str,
    ) -> None: ...
    def step(
        self, name: str, command_topic: str, reply_topic: str
    ) -> "SagaBuilder": ...
    def with_compensation(self, compensation: str) -> "SagaBuilder": ...
    def with_step_timeout(self, timeout: str) -> "SagaBuilder": ...
    def build(self) -> SagaConfig: ...

class IdempotencyKey:
    @staticmethod
    def generate(scope: str) -> "IdempotencyKey": ...
    @staticmethod
    def wrap(key: str) -> "IdempotencyKey": ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class IdempotencyRecord:
    key: str
    status_code: int
    body: str
    created_at: str
    def __init__(
        self, key: IdempotencyKey, status_code: int, body: Any
    ) -> None: ...

class IdempotencyStore:
    def __init__(self) -> None: ...
    def get(self, key: str) -> Optional[str]: ...
    def set_nx(self, key: str, body: str, ttl_secs: int) -> bool: ...
    def __len__(self) -> int: ...

class AggregateRoot:
    id: str
    version: int
    def __init__(self, aggregate_cls: type, aggregate_id: str) -> None: ...
    @staticmethod
    def rehydrate(
        aggregate_cls: type, aggregate_id: str, events: list[dict]
    ) -> "AggregateRoot": ...
    def apply_new(self, event: dict) -> None: ...
    def take_pending_events(self) -> list[dict]: ...
    def pending_count(self) -> int: ...

def lookup(store: IdempotencyStore, key: str) -> Optional[str]: ...
def store_result(
    store: IdempotencyStore, key: str, body: str, ttl_secs: Optional[int] = None
) -> bool: ...
